/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept'
import { Route as InternalDomainCheckRouteImport } from './routes/internal/domain-check'
import { Route as CliLoginRouteImport } from './routes/cli.login'
import { Route as ApiSubdomainsRouteImport } from './routes/api/subdomains'
import { Route as ApiRequestsRouteImport } from './routes/api/requests'
import { Route as ApiAuthTokensRouteImport } from './routes/api/auth-tokens'
import { Route as OrgSlugSubdomainsRouteImport } from './routes/$orgSlug/subdomains'
import { Route as OrgSlugSettingsRouteImport } from './routes/$orgSlug/settings'
import { Route as OrgSlugRequestsRouteImport } from './routes/$orgSlug/requests'
import { Route as OrgSlugMembersRouteImport } from './routes/$orgSlug/members'
import { Route as OrgSlugInstallRouteImport } from './routes/$orgSlug/install'
import { Route as OrgSlugDomainsRouteImport } from './routes/$orgSlug/domains'
import { Route as OrgSlugBillingRouteImport } from './routes/$orgSlug/billing'
import { Route as ApiTunnelsIndexRouteImport } from './routes/api/tunnels/index'
import { Route as ApiDomainsIndexRouteImport } from './routes/api/domains/index'
import { Route as OrgSlugTunnelsIndexRouteImport } from './routes/$orgSlug/tunnels/index'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug/settings/index'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiTunnelsTunnelIdRouteImport } from './routes/api/tunnels/$tunnelId'
import { Route as ApiTunnelRegisterRouteImport } from './routes/api/tunnel/register'
import { Route as ApiTunnelCheckSubdomainRouteImport } from './routes/api/tunnel/check-subdomain'
import { Route as ApiTunnelAuthRouteImport } from './routes/api/tunnel/auth'
import { Route as ApiSubscriptionsOrganizationIdRouteImport } from './routes/api/subscriptions/$organizationId'
import { Route as ApiSubdomainsSubdomainIdRouteImport } from './routes/api/subdomains/$subdomainId'
import { Route as ApiStatsTunnelRouteImport } from './routes/api/stats/tunnel'
import { Route as ApiStatsOverviewRouteImport } from './routes/api/stats/overview'
import { Route as ApiStatsBandwidthRouteImport } from './routes/api/stats/bandwidth'
import { Route as ApiPortalPolarRouteImport } from './routes/api/portal/polar'
import { Route as ApiOrganizationsCheckSlugRouteImport } from './routes/api/organizations/check-slug'
import { Route as ApiMeOrgsRouteImport } from './routes/api/me/orgs'
import { Route as ApiDomainsDomainIdRouteImport } from './routes/api/domains/$domainId'
import { Route as ApiDomainVerifyOwnershipRouteImport } from './routes/api/domain/verify-ownership'
import { Route as ApiCliLoginRouteImport } from './routes/api/cli/login'
import { Route as ApiCliExchangeRouteImport } from './routes/api/cli/exchange'
import { Route as ApiCliCompleteRouteImport } from './routes/api/cli/complete'
import { Route as ApiCheckoutPolarRouteImport } from './routes/api/checkout/polar'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as OrgSlugTunnelsTunnelIdRouteImport } from './routes/$orgSlug/tunnels/$tunnelId'
import { Route as OrgSlugSettingsProfileRouteImport } from './routes/$orgSlug/settings/profile'
import { Route as OrgSlugSettingsOrganizationRouteImport } from './routes/$orgSlug/settings/organization'
import { Route as ApiTunnelsTunnelIdStopRouteImport } from './routes/api/tunnels/$tunnelId.stop'
import { Route as ApiDomainsDomainIdVerifyRouteImport } from './routes/api/domains/$domainId.verify'
import { Route as ApiCliLoginStatusRouteImport } from './routes/api/cli/login/status'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalDomainCheckRoute = InternalDomainCheckRouteImport.update({
  id: '/internal/domain-check',
  path: '/internal/domain-check',
  getParentRoute: () => rootRouteImport,
} as any)
const CliLoginRoute = CliLoginRouteImport.update({
  id: '/cli/login',
  path: '/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubdomainsRoute = ApiSubdomainsRouteImport.update({
  id: '/api/subdomains',
  path: '/api/subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTokensRoute = ApiAuthTokensRouteImport.update({
  id: '/api/auth-tokens',
  path: '/api/auth-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugSubdomainsRoute = OrgSlugSubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsRoute = OrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugRequestsRoute = OrgSlugRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugMembersRoute = OrgSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugInstallRoute = OrgSlugInstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugDomainsRoute = OrgSlugDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugBillingRoute = OrgSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgSlugRoute,
} as any)
const ApiTunnelsIndexRoute = ApiTunnelsIndexRouteImport.update({
  id: '/api/tunnels/',
  path: '/api/tunnels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainsIndexRoute = ApiDomainsIndexRouteImport.update({
  id: '/api/domains/',
  path: '/api/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugTunnelsIndexRoute = OrgSlugTunnelsIndexRouteImport.update({
  id: '/tunnels/',
  path: '/tunnels/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelsTunnelIdRoute = ApiTunnelsTunnelIdRouteImport.update({
  id: '/api/tunnels/$tunnelId',
  path: '/api/tunnels/$tunnelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelRegisterRoute = ApiTunnelRegisterRouteImport.update({
  id: '/api/tunnel/register',
  path: '/api/tunnel/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelCheckSubdomainRoute = ApiTunnelCheckSubdomainRouteImport.update({
  id: '/api/tunnel/check-subdomain',
  path: '/api/tunnel/check-subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelAuthRoute = ApiTunnelAuthRouteImport.update({
  id: '/api/tunnel/auth',
  path: '/api/tunnel/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionsOrganizationIdRoute =
  ApiSubscriptionsOrganizationIdRouteImport.update({
    id: '/api/subscriptions/$organizationId',
    path: '/api/subscriptions/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSubdomainsSubdomainIdRoute =
  ApiSubdomainsSubdomainIdRouteImport.update({
    id: '/$subdomainId',
    path: '/$subdomainId',
    getParentRoute: () => ApiSubdomainsRoute,
  } as any)
const ApiStatsTunnelRoute = ApiStatsTunnelRouteImport.update({
  id: '/api/stats/tunnel',
  path: '/api/stats/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsOverviewRoute = ApiStatsOverviewRouteImport.update({
  id: '/api/stats/overview',
  path: '/api/stats/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsBandwidthRoute = ApiStatsBandwidthRouteImport.update({
  id: '/api/stats/bandwidth',
  path: '/api/stats/bandwidth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalPolarRoute = ApiPortalPolarRouteImport.update({
  id: '/api/portal/polar',
  path: '/api/portal/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrganizationsCheckSlugRoute =
  ApiOrganizationsCheckSlugRouteImport.update({
    id: '/api/organizations/check-slug',
    path: '/api/organizations/check-slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMeOrgsRoute = ApiMeOrgsRouteImport.update({
  id: '/api/me/orgs',
  path: '/api/me/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainsDomainIdRoute = ApiDomainsDomainIdRouteImport.update({
  id: '/api/domains/$domainId',
  path: '/api/domains/$domainId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainVerifyOwnershipRoute =
  ApiDomainVerifyOwnershipRouteImport.update({
    id: '/api/domain/verify-ownership',
    path: '/api/domain/verify-ownership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCliLoginRoute = ApiCliLoginRouteImport.update({
  id: '/api/cli/login',
  path: '/api/cli/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliExchangeRoute = ApiCliExchangeRouteImport.update({
  id: '/api/cli/exchange',
  path: '/api/cli/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliCompleteRoute = ApiCliCompleteRouteImport.update({
  id: '/api/cli/complete',
  path: '/api/cli/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutPolarRoute = ApiCheckoutPolarRouteImport.update({
  id: '/api/checkout/polar',
  path: '/api/checkout/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugTunnelsTunnelIdRoute = OrgSlugTunnelsTunnelIdRouteImport.update({
  id: '/tunnels/$tunnelId',
  path: '/tunnels/$tunnelId',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsProfileRoute = OrgSlugSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const OrgSlugSettingsOrganizationRoute =
  OrgSlugSettingsOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => OrgSlugSettingsRoute,
  } as any)
const ApiTunnelsTunnelIdStopRoute = ApiTunnelsTunnelIdStopRouteImport.update({
  id: '/stop',
  path: '/stop',
  getParentRoute: () => ApiTunnelsTunnelIdRoute,
} as any)
const ApiDomainsDomainIdVerifyRoute =
  ApiDomainsDomainIdVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => ApiDomainsDomainIdRoute,
  } as any)
const ApiCliLoginStatusRoute = ApiCliLoginStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiCliLoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/subdomains': typeof OrgSlugSubdomainsRoute
  '/api/auth-tokens': typeof ApiAuthTokensRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/subdomains': typeof ApiSubdomainsRouteWithChildren
  '/cli/login': typeof CliLoginRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/domains/$domainId': typeof ApiDomainsDomainIdRouteWithChildren
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/portal/polar': typeof ApiPortalPolarRoute
  '/api/stats/bandwidth': typeof ApiStatsBandwidthRoute
  '/api/stats/overview': typeof ApiStatsOverviewRoute
  '/api/stats/tunnel': typeof ApiStatsTunnelRoute
  '/api/subdomains/$subdomainId': typeof ApiSubdomainsSubdomainIdRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/tunnels/$tunnelId': typeof ApiTunnelsTunnelIdRouteWithChildren
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels': typeof OrgSlugTunnelsIndexRoute
  '/api/domains': typeof ApiDomainsIndexRoute
  '/api/tunnels': typeof ApiTunnelsIndexRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/domains/$domainId/verify': typeof ApiDomainsDomainIdVerifyRoute
  '/api/tunnels/$tunnelId/stop': typeof ApiTunnelsTunnelIdStopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/subdomains': typeof OrgSlugSubdomainsRoute
  '/api/auth-tokens': typeof ApiAuthTokensRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/subdomains': typeof ApiSubdomainsRouteWithChildren
  '/cli/login': typeof CliLoginRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/domains/$domainId': typeof ApiDomainsDomainIdRouteWithChildren
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/portal/polar': typeof ApiPortalPolarRoute
  '/api/stats/bandwidth': typeof ApiStatsBandwidthRoute
  '/api/stats/overview': typeof ApiStatsOverviewRoute
  '/api/stats/tunnel': typeof ApiStatsTunnelRoute
  '/api/subdomains/$subdomainId': typeof ApiSubdomainsSubdomainIdRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/tunnels/$tunnelId': typeof ApiTunnelsTunnelIdRouteWithChildren
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels': typeof OrgSlugTunnelsIndexRoute
  '/api/domains': typeof ApiDomainsIndexRoute
  '/api/tunnels': typeof ApiTunnelsIndexRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/domains/$domainId/verify': typeof ApiDomainsDomainIdVerifyRoute
  '/api/tunnels/$tunnelId/stop': typeof ApiTunnelsTunnelIdStopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/$orgSlug/billing': typeof OrgSlugBillingRoute
  '/$orgSlug/domains': typeof OrgSlugDomainsRoute
  '/$orgSlug/install': typeof OrgSlugInstallRoute
  '/$orgSlug/members': typeof OrgSlugMembersRoute
  '/$orgSlug/requests': typeof OrgSlugRequestsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/subdomains': typeof OrgSlugSubdomainsRoute
  '/api/auth-tokens': typeof ApiAuthTokensRoute
  '/api/requests': typeof ApiRequestsRoute
  '/api/subdomains': typeof ApiSubdomainsRouteWithChildren
  '/cli/login': typeof CliLoginRoute
  '/internal/domain-check': typeof InternalDomainCheckRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/organization': typeof OrgSlugSettingsOrganizationRoute
  '/$orgSlug/settings/profile': typeof OrgSlugSettingsProfileRoute
  '/$orgSlug/tunnels/$tunnelId': typeof OrgSlugTunnelsTunnelIdRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/checkout/polar': typeof ApiCheckoutPolarRoute
  '/api/cli/complete': typeof ApiCliCompleteRoute
  '/api/cli/exchange': typeof ApiCliExchangeRoute
  '/api/cli/login': typeof ApiCliLoginRouteWithChildren
  '/api/domain/verify-ownership': typeof ApiDomainVerifyOwnershipRoute
  '/api/domains/$domainId': typeof ApiDomainsDomainIdRouteWithChildren
  '/api/me/orgs': typeof ApiMeOrgsRoute
  '/api/organizations/check-slug': typeof ApiOrganizationsCheckSlugRoute
  '/api/portal/polar': typeof ApiPortalPolarRoute
  '/api/stats/bandwidth': typeof ApiStatsBandwidthRoute
  '/api/stats/overview': typeof ApiStatsOverviewRoute
  '/api/stats/tunnel': typeof ApiStatsTunnelRoute
  '/api/subdomains/$subdomainId': typeof ApiSubdomainsSubdomainIdRoute
  '/api/subscriptions/$organizationId': typeof ApiSubscriptionsOrganizationIdRoute
  '/api/tunnel/auth': typeof ApiTunnelAuthRoute
  '/api/tunnel/check-subdomain': typeof ApiTunnelCheckSubdomainRoute
  '/api/tunnel/register': typeof ApiTunnelRegisterRoute
  '/api/tunnels/$tunnelId': typeof ApiTunnelsTunnelIdRouteWithChildren
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/tunnels/': typeof OrgSlugTunnelsIndexRoute
  '/api/domains/': typeof ApiDomainsIndexRoute
  '/api/tunnels/': typeof ApiTunnelsIndexRoute
  '/api/cli/login/status': typeof ApiCliLoginStatusRoute
  '/api/domains/$domainId/verify': typeof ApiDomainsDomainIdVerifyRoute
  '/api/tunnels/$tunnelId/stop': typeof ApiTunnelsTunnelIdStopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/settings'
    | '/$orgSlug/subdomains'
    | '/api/auth-tokens'
    | '/api/requests'
    | '/api/subdomains'
    | '/cli/login'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/domains/$domainId'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/portal/polar'
    | '/api/stats/bandwidth'
    | '/api/stats/overview'
    | '/api/stats/tunnel'
    | '/api/subdomains/$subdomainId'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/tunnels/$tunnelId'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tunnels'
    | '/api/domains'
    | '/api/tunnels'
    | '/api/cli/login/status'
    | '/api/domains/$domainId/verify'
    | '/api/tunnels/$tunnelId/stop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/subdomains'
    | '/api/auth-tokens'
    | '/api/requests'
    | '/api/subdomains'
    | '/cli/login'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/domains/$domainId'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/portal/polar'
    | '/api/stats/bandwidth'
    | '/api/stats/overview'
    | '/api/stats/tunnel'
    | '/api/subdomains/$subdomainId'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/tunnels/$tunnelId'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings'
    | '/$orgSlug/tunnels'
    | '/api/domains'
    | '/api/tunnels'
    | '/api/cli/login/status'
    | '/api/domains/$domainId/verify'
    | '/api/tunnels/$tunnelId/stop'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/$orgSlug/billing'
    | '/$orgSlug/domains'
    | '/$orgSlug/install'
    | '/$orgSlug/members'
    | '/$orgSlug/requests'
    | '/$orgSlug/settings'
    | '/$orgSlug/subdomains'
    | '/api/auth-tokens'
    | '/api/requests'
    | '/api/subdomains'
    | '/cli/login'
    | '/internal/domain-check'
    | '/invitations/accept'
    | '/$orgSlug/'
    | '/$orgSlug/settings/organization'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/tunnels/$tunnelId'
    | '/api/admin/login'
    | '/api/admin/stats'
    | '/api/auth/$'
    | '/api/checkout/polar'
    | '/api/cli/complete'
    | '/api/cli/exchange'
    | '/api/cli/login'
    | '/api/domain/verify-ownership'
    | '/api/domains/$domainId'
    | '/api/me/orgs'
    | '/api/organizations/check-slug'
    | '/api/portal/polar'
    | '/api/stats/bandwidth'
    | '/api/stats/overview'
    | '/api/stats/tunnel'
    | '/api/subdomains/$subdomainId'
    | '/api/subscriptions/$organizationId'
    | '/api/tunnel/auth'
    | '/api/tunnel/check-subdomain'
    | '/api/tunnel/register'
    | '/api/tunnels/$tunnelId'
    | '/api/webhooks/polar'
    | '/$orgSlug/settings/'
    | '/$orgSlug/tunnels/'
    | '/api/domains/'
    | '/api/tunnels/'
    | '/api/cli/login/status'
    | '/api/domains/$domainId/verify'
    | '/api/tunnels/$tunnelId/stop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthTokensRoute: typeof ApiAuthTokensRoute
  ApiRequestsRoute: typeof ApiRequestsRoute
  ApiSubdomainsRoute: typeof ApiSubdomainsRouteWithChildren
  CliLoginRoute: typeof CliLoginRoute
  InternalDomainCheckRoute: typeof InternalDomainCheckRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCheckoutPolarRoute: typeof ApiCheckoutPolarRoute
  ApiCliCompleteRoute: typeof ApiCliCompleteRoute
  ApiCliExchangeRoute: typeof ApiCliExchangeRoute
  ApiCliLoginRoute: typeof ApiCliLoginRouteWithChildren
  ApiDomainVerifyOwnershipRoute: typeof ApiDomainVerifyOwnershipRoute
  ApiDomainsDomainIdRoute: typeof ApiDomainsDomainIdRouteWithChildren
  ApiMeOrgsRoute: typeof ApiMeOrgsRoute
  ApiOrganizationsCheckSlugRoute: typeof ApiOrganizationsCheckSlugRoute
  ApiPortalPolarRoute: typeof ApiPortalPolarRoute
  ApiStatsBandwidthRoute: typeof ApiStatsBandwidthRoute
  ApiStatsOverviewRoute: typeof ApiStatsOverviewRoute
  ApiStatsTunnelRoute: typeof ApiStatsTunnelRoute
  ApiSubscriptionsOrganizationIdRoute: typeof ApiSubscriptionsOrganizationIdRoute
  ApiTunnelAuthRoute: typeof ApiTunnelAuthRoute
  ApiTunnelCheckSubdomainRoute: typeof ApiTunnelCheckSubdomainRoute
  ApiTunnelRegisterRoute: typeof ApiTunnelRegisterRoute
  ApiTunnelsTunnelIdRoute: typeof ApiTunnelsTunnelIdRouteWithChildren
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
  ApiDomainsIndexRoute: typeof ApiDomainsIndexRoute
  ApiTunnelsIndexRoute: typeof ApiTunnelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/domain-check': {
      id: '/internal/domain-check'
      path: '/internal/domain-check'
      fullPath: '/internal/domain-check'
      preLoaderRoute: typeof InternalDomainCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/login': {
      id: '/cli/login'
      path: '/cli/login'
      fullPath: '/cli/login'
      preLoaderRoute: typeof CliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subdomains': {
      id: '/api/subdomains'
      path: '/api/subdomains'
      fullPath: '/api/subdomains'
      preLoaderRoute: typeof ApiSubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-tokens': {
      id: '/api/auth-tokens'
      path: '/api/auth-tokens'
      fullPath: '/api/auth-tokens'
      preLoaderRoute: typeof ApiAuthTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/subdomains': {
      id: '/$orgSlug/subdomains'
      path: '/subdomains'
      fullPath: '/$orgSlug/subdomains'
      preLoaderRoute: typeof OrgSlugSubdomainsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/requests': {
      id: '/$orgSlug/requests'
      path: '/requests'
      fullPath: '/$orgSlug/requests'
      preLoaderRoute: typeof OrgSlugRequestsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/members': {
      id: '/$orgSlug/members'
      path: '/members'
      fullPath: '/$orgSlug/members'
      preLoaderRoute: typeof OrgSlugMembersRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/install': {
      id: '/$orgSlug/install'
      path: '/install'
      fullPath: '/$orgSlug/install'
      preLoaderRoute: typeof OrgSlugInstallRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/domains': {
      id: '/$orgSlug/domains'
      path: '/domains'
      fullPath: '/$orgSlug/domains'
      preLoaderRoute: typeof OrgSlugDomainsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/billing': {
      id: '/$orgSlug/billing'
      path: '/billing'
      fullPath: '/$orgSlug/billing'
      preLoaderRoute: typeof OrgSlugBillingRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/api/tunnels/': {
      id: '/api/tunnels/'
      path: '/api/tunnels'
      fullPath: '/api/tunnels'
      preLoaderRoute: typeof ApiTunnelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domains/': {
      id: '/api/domains/'
      path: '/api/domains'
      fullPath: '/api/domains'
      preLoaderRoute: typeof ApiDomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/tunnels/': {
      id: '/$orgSlug/tunnels/'
      path: '/tunnels'
      fullPath: '/$orgSlug/tunnels'
      preLoaderRoute: typeof OrgSlugTunnelsIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnels/$tunnelId': {
      id: '/api/tunnels/$tunnelId'
      path: '/api/tunnels/$tunnelId'
      fullPath: '/api/tunnels/$tunnelId'
      preLoaderRoute: typeof ApiTunnelsTunnelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/register': {
      id: '/api/tunnel/register'
      path: '/api/tunnel/register'
      fullPath: '/api/tunnel/register'
      preLoaderRoute: typeof ApiTunnelRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/check-subdomain': {
      id: '/api/tunnel/check-subdomain'
      path: '/api/tunnel/check-subdomain'
      fullPath: '/api/tunnel/check-subdomain'
      preLoaderRoute: typeof ApiTunnelCheckSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel/auth': {
      id: '/api/tunnel/auth'
      path: '/api/tunnel/auth'
      fullPath: '/api/tunnel/auth'
      preLoaderRoute: typeof ApiTunnelAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscriptions/$organizationId': {
      id: '/api/subscriptions/$organizationId'
      path: '/api/subscriptions/$organizationId'
      fullPath: '/api/subscriptions/$organizationId'
      preLoaderRoute: typeof ApiSubscriptionsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subdomains/$subdomainId': {
      id: '/api/subdomains/$subdomainId'
      path: '/$subdomainId'
      fullPath: '/api/subdomains/$subdomainId'
      preLoaderRoute: typeof ApiSubdomainsSubdomainIdRouteImport
      parentRoute: typeof ApiSubdomainsRoute
    }
    '/api/stats/tunnel': {
      id: '/api/stats/tunnel'
      path: '/api/stats/tunnel'
      fullPath: '/api/stats/tunnel'
      preLoaderRoute: typeof ApiStatsTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/overview': {
      id: '/api/stats/overview'
      path: '/api/stats/overview'
      fullPath: '/api/stats/overview'
      preLoaderRoute: typeof ApiStatsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats/bandwidth': {
      id: '/api/stats/bandwidth'
      path: '/api/stats/bandwidth'
      fullPath: '/api/stats/bandwidth'
      preLoaderRoute: typeof ApiStatsBandwidthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/polar': {
      id: '/api/portal/polar'
      path: '/api/portal/polar'
      fullPath: '/api/portal/polar'
      preLoaderRoute: typeof ApiPortalPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/organizations/check-slug': {
      id: '/api/organizations/check-slug'
      path: '/api/organizations/check-slug'
      fullPath: '/api/organizations/check-slug'
      preLoaderRoute: typeof ApiOrganizationsCheckSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/orgs': {
      id: '/api/me/orgs'
      path: '/api/me/orgs'
      fullPath: '/api/me/orgs'
      preLoaderRoute: typeof ApiMeOrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domains/$domainId': {
      id: '/api/domains/$domainId'
      path: '/api/domains/$domainId'
      fullPath: '/api/domains/$domainId'
      preLoaderRoute: typeof ApiDomainsDomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domain/verify-ownership': {
      id: '/api/domain/verify-ownership'
      path: '/api/domain/verify-ownership'
      fullPath: '/api/domain/verify-ownership'
      preLoaderRoute: typeof ApiDomainVerifyOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/login': {
      id: '/api/cli/login'
      path: '/api/cli/login'
      fullPath: '/api/cli/login'
      preLoaderRoute: typeof ApiCliLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/exchange': {
      id: '/api/cli/exchange'
      path: '/api/cli/exchange'
      fullPath: '/api/cli/exchange'
      preLoaderRoute: typeof ApiCliExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/complete': {
      id: '/api/cli/complete'
      path: '/api/cli/complete'
      fullPath: '/api/cli/complete'
      preLoaderRoute: typeof ApiCliCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/polar': {
      id: '/api/checkout/polar'
      path: '/api/checkout/polar'
      fullPath: '/api/checkout/polar'
      preLoaderRoute: typeof ApiCheckoutPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/tunnels/$tunnelId': {
      id: '/$orgSlug/tunnels/$tunnelId'
      path: '/tunnels/$tunnelId'
      fullPath: '/$orgSlug/tunnels/$tunnelId'
      preLoaderRoute: typeof OrgSlugTunnelsTunnelIdRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings/profile': {
      id: '/$orgSlug/settings/profile'
      path: '/profile'
      fullPath: '/$orgSlug/settings/profile'
      preLoaderRoute: typeof OrgSlugSettingsProfileRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/organization': {
      id: '/$orgSlug/settings/organization'
      path: '/organization'
      fullPath: '/$orgSlug/settings/organization'
      preLoaderRoute: typeof OrgSlugSettingsOrganizationRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/api/tunnels/$tunnelId/stop': {
      id: '/api/tunnels/$tunnelId/stop'
      path: '/stop'
      fullPath: '/api/tunnels/$tunnelId/stop'
      preLoaderRoute: typeof ApiTunnelsTunnelIdStopRouteImport
      parentRoute: typeof ApiTunnelsTunnelIdRoute
    }
    '/api/domains/$domainId/verify': {
      id: '/api/domains/$domainId/verify'
      path: '/verify'
      fullPath: '/api/domains/$domainId/verify'
      preLoaderRoute: typeof ApiDomainsDomainIdVerifyRouteImport
      parentRoute: typeof ApiDomainsDomainIdRoute
    }
    '/api/cli/login/status': {
      id: '/api/cli/login/status'
      path: '/status'
      fullPath: '/api/cli/login/status'
      preLoaderRoute: typeof ApiCliLoginStatusRouteImport
      parentRoute: typeof ApiCliLoginRoute
    }
  }
}

interface OrgSlugSettingsRouteChildren {
  OrgSlugSettingsOrganizationRoute: typeof OrgSlugSettingsOrganizationRoute
  OrgSlugSettingsProfileRoute: typeof OrgSlugSettingsProfileRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugSettingsRouteChildren: OrgSlugSettingsRouteChildren = {
  OrgSlugSettingsOrganizationRoute: OrgSlugSettingsOrganizationRoute,
  OrgSlugSettingsProfileRoute: OrgSlugSettingsProfileRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugSettingsRouteWithChildren = OrgSlugSettingsRoute._addFileChildren(
  OrgSlugSettingsRouteChildren,
)

interface OrgSlugRouteChildren {
  OrgSlugBillingRoute: typeof OrgSlugBillingRoute
  OrgSlugDomainsRoute: typeof OrgSlugDomainsRoute
  OrgSlugInstallRoute: typeof OrgSlugInstallRoute
  OrgSlugMembersRoute: typeof OrgSlugMembersRoute
  OrgSlugRequestsRoute: typeof OrgSlugRequestsRoute
  OrgSlugSettingsRoute: typeof OrgSlugSettingsRouteWithChildren
  OrgSlugSubdomainsRoute: typeof OrgSlugSubdomainsRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugTunnelsTunnelIdRoute: typeof OrgSlugTunnelsTunnelIdRoute
  OrgSlugTunnelsIndexRoute: typeof OrgSlugTunnelsIndexRoute
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugBillingRoute: OrgSlugBillingRoute,
  OrgSlugDomainsRoute: OrgSlugDomainsRoute,
  OrgSlugInstallRoute: OrgSlugInstallRoute,
  OrgSlugMembersRoute: OrgSlugMembersRoute,
  OrgSlugRequestsRoute: OrgSlugRequestsRoute,
  OrgSlugSettingsRoute: OrgSlugSettingsRouteWithChildren,
  OrgSlugSubdomainsRoute: OrgSlugSubdomainsRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugTunnelsTunnelIdRoute: OrgSlugTunnelsTunnelIdRoute,
  OrgSlugTunnelsIndexRoute: OrgSlugTunnelsIndexRoute,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

interface ApiSubdomainsRouteChildren {
  ApiSubdomainsSubdomainIdRoute: typeof ApiSubdomainsSubdomainIdRoute
}

const ApiSubdomainsRouteChildren: ApiSubdomainsRouteChildren = {
  ApiSubdomainsSubdomainIdRoute: ApiSubdomainsSubdomainIdRoute,
}

const ApiSubdomainsRouteWithChildren = ApiSubdomainsRoute._addFileChildren(
  ApiSubdomainsRouteChildren,
)

interface ApiCliLoginRouteChildren {
  ApiCliLoginStatusRoute: typeof ApiCliLoginStatusRoute
}

const ApiCliLoginRouteChildren: ApiCliLoginRouteChildren = {
  ApiCliLoginStatusRoute: ApiCliLoginStatusRoute,
}

const ApiCliLoginRouteWithChildren = ApiCliLoginRoute._addFileChildren(
  ApiCliLoginRouteChildren,
)

interface ApiDomainsDomainIdRouteChildren {
  ApiDomainsDomainIdVerifyRoute: typeof ApiDomainsDomainIdVerifyRoute
}

const ApiDomainsDomainIdRouteChildren: ApiDomainsDomainIdRouteChildren = {
  ApiDomainsDomainIdVerifyRoute: ApiDomainsDomainIdVerifyRoute,
}

const ApiDomainsDomainIdRouteWithChildren =
  ApiDomainsDomainIdRoute._addFileChildren(ApiDomainsDomainIdRouteChildren)

interface ApiTunnelsTunnelIdRouteChildren {
  ApiTunnelsTunnelIdStopRoute: typeof ApiTunnelsTunnelIdStopRoute
}

const ApiTunnelsTunnelIdRouteChildren: ApiTunnelsTunnelIdRouteChildren = {
  ApiTunnelsTunnelIdStopRoute: ApiTunnelsTunnelIdStopRoute,
}

const ApiTunnelsTunnelIdRouteWithChildren =
  ApiTunnelsTunnelIdRoute._addFileChildren(ApiTunnelsTunnelIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthTokensRoute: ApiAuthTokensRoute,
  ApiRequestsRoute: ApiRequestsRoute,
  ApiSubdomainsRoute: ApiSubdomainsRouteWithChildren,
  CliLoginRoute: CliLoginRoute,
  InternalDomainCheckRoute: InternalDomainCheckRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCheckoutPolarRoute: ApiCheckoutPolarRoute,
  ApiCliCompleteRoute: ApiCliCompleteRoute,
  ApiCliExchangeRoute: ApiCliExchangeRoute,
  ApiCliLoginRoute: ApiCliLoginRouteWithChildren,
  ApiDomainVerifyOwnershipRoute: ApiDomainVerifyOwnershipRoute,
  ApiDomainsDomainIdRoute: ApiDomainsDomainIdRouteWithChildren,
  ApiMeOrgsRoute: ApiMeOrgsRoute,
  ApiOrganizationsCheckSlugRoute: ApiOrganizationsCheckSlugRoute,
  ApiPortalPolarRoute: ApiPortalPolarRoute,
  ApiStatsBandwidthRoute: ApiStatsBandwidthRoute,
  ApiStatsOverviewRoute: ApiStatsOverviewRoute,
  ApiStatsTunnelRoute: ApiStatsTunnelRoute,
  ApiSubscriptionsOrganizationIdRoute: ApiSubscriptionsOrganizationIdRoute,
  ApiTunnelAuthRoute: ApiTunnelAuthRoute,
  ApiTunnelCheckSubdomainRoute: ApiTunnelCheckSubdomainRoute,
  ApiTunnelRegisterRoute: ApiTunnelRegisterRoute,
  ApiTunnelsTunnelIdRoute: ApiTunnelsTunnelIdRouteWithChildren,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
  ApiDomainsIndexRoute: ApiDomainsIndexRoute,
  ApiTunnelsIndexRoute: ApiTunnelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
